name: excel-to-pandas
channels:
    - conda-forge
dependencies:
  - jupyter=1.0
  - matplotlib=3.1.3
  - numpy=1.18
  - pandas=1.0.3
  - qgrid=1.3.1
  - rise=5.6.1
  - seaborn=0.10.1
  - xlsxwriter=1.2.9
